apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        componet: api
    spec:
      containers:
        - name: api
          image: fhsincy/notes-api
          ports:
            - containerPort: 3000